---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: silly-demo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:mitin20/argo-events-gh-demo.git
    targetRevision: HEAD
    path: silly-demo
  destination:
    server: https://kubernetes.default.svc
    namespace: a-team
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
      allowEmpty: true
